### ISSUE TITLE
Debouncing: Bad state: No element

### ISSUE THREAD

**Issue by koutja** [PlugFox/throttling#7]
An error occurs if you run the code in DartPad.dev from the test example:

Uncaught Error: Bad state: No element
Uncaught Error: Bad state: Cannot add new events after calling close

```dart
final deb = Debouncing(duration: const Duration(seconds: 2));
deb.debounce(() {print(' * ping #1');});
await Future<void>.delayed(const Duration(seconds: 1));
deb.debounce(() {print(' * ping #2');});
await Future<void>.delayed(const Duration(seconds: 1));
deb.debounce(() {print(' * ping #3');});
await deb.close();
```

**Comment by Mik77o** [comment]
We encounter same problem:

```
I/flutter ( 7479): ================ Error dispatched to Datadog ================
I/flutter ( 7479): Bad state: No element
I/flutter ( 7479): #0      Stream.first.<anonymous closure> (dart:async/stream.dart:1575:9)
I/flutter ( 7479): #1      _rootRun (dart:async/zone.dart:1391:47)
I/flutter ( 7479): #2      _CustomZone.run (dart:async/zone.dart:1301:19)
I/flutter ( 7479): #3      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
I/flutter ( 7479): #4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
I/flutter ( 7479): #5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
I/flutter ( 7479): #6      _DelayedDone.perform (dart:async/stream_impl.dart:534:14)
I/flutter ( 7479): #7      _PendingEvents.handleNext (dart:async/stream_impl.dart:620:11)
I/flutter ( 7479): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591:7)
I/flutter ( 7479): #9      _rootRun (dart:async/zone.dart:1391:47)
I/flutter ( 7479): #10     _CustomZone.run (dart:async/zone.dart:1301:19)
I/flutter ( 7479): #11     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
I/flutter ( 7479): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
I/flutter ( 7479): #13     _rootRun (dart:async/zone.dart:1399:13)
I/flutter ( 7479): #14     _CustomZone.run (dart:async/zone.dart:1301:19)
I/flutter ( 7479): #15     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
I/flutter ( 7479): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
I/flutter ( 7479): #17     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
I/flutter ( 7479): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
I/flutter ( 7479): ================ Error dispatched to Datadog ================
I/flutter ( 7479): Bad state: Cannot add new events after calling close
I/flutter ( 7479): #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:243:24)
I/flutter ( 7479): #1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:876:13)
I/flutter ( 7479): #2      Debouncing.debounce.<anonymous closure> (package:throttling/src/debounce.dart:50:21)
debounce.dart:50
I/flutter ( 7479): #3      _rootRun (dart:async/zone.dart:1391:47)
I/flutter ( 7479): #4      _CustomZone.run (dart:async/zone.dart:1301:19)
I/flutter ( 7479): #5      _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
I/flutter ( 7479): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
I/flutter ( 7479): #7      _rootRun (dart:async/zone.dart:1399:13)
I/flutter ( 7479): #8      _CustomZone.run (dart:async/zone.dart:1301:19)
I/flutter ( 7479): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1233:23)
I/flutter ( 7479): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
I/flutter ( 7479): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
I/flutter ( 7479): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
I/flutter ( 7479): #13     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
```

**Comment by PlugFox** [comment]
@koutja @Mik77o I'll fix it today, add few tests and will create a new major release with Dart 3.0.0

**Comment by PlugFox** [comment]
[New version 2.0.0](https://pub.dev/packages/throttling)
